---
title: "Gov 1005 4/5 Milestone for Final Project"
author: "Evelyn Cai"
date: "April 5, 2019"
output: html_document
---

```{r setup_libraries, include=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Load libraries

library(tidyverse)
library(janitor)
library(rebus)
library(ggmap)
library(ggthemes)
library(gganimate)
```

```{r setup_x, warning = FALSE, message = FALSE}

# Read in the CSV file visa read_csv

x <- read_csv("survivor.csv",
              
              # specify the column types, or else they will be read in as characters
              
              col_types = cols(
                
              # Specify the number of days as a double
                
              daysLasted = col_double(),
              
              # Also specify that the number of total votes one received is a double
              
              votesAgainst = col_double(),
              
              # Specify that the number of tribal challenge wins is a double
              
              tribalChallengeWins = col_double(),
              individualChallengeWins = col_double())) %>%
  
  # Unselect columns that pertain to player trivia, as they are strings of
  # interesting facts that do not contribute to our data.
  
  select(-(contains("trivia"))) 
```


```{r cleanup, message = FALSE, error = FALSE}

survivor_data <- x %>%
  
    # Rename runner-ups to 2nd place, sole survivors to 1st place, and recode
    # from character strings to doubles
  
    mutate(finish = fct_recode(finish,
                               `1` = "Sole Survivor",
                               `2` = "Runner-Up",
                               `2` = "Co-Runner-Up",
                               `3` = "2nd Runner-Up",
                               `3` = "3rd",
                               `4` = "4th",
                               `5` = "5th",
                               `6` = "6th",
                               `7` = "7th",
                               `8` = "8th",
                               `9` = "9th",
                               `10` = "10th",
                               `11` = "11th",
                               `12` = "12th",
                               `13` = "13th",
                               `14` = "14th",
                               `15` = "15th",
                               `16` = "16th",                                
                               `17` = "17th",
                               `18` = "18th",
                               `19` = "19th",
                               `20` = "20th"),
             
             # Create a new column using case_when that encodes for the number
             # of a season based on the title of the season
             
             season_number = case_when(
               season == "Borneo" ~ 1,
               season == "The Australian Outback" ~ 2,
               season == "Africa" ~ 3,
               season == "Marquesas" ~ 4,
               season == "Thailand" ~ 5,
               season == "The Amazon" ~ 6,
               season == "Pearl Islands" ~ 7,
               season == "All-Stars" ~ 8,
               season == "Vanuatu" ~ 9,
               season == "Palau" ~ 10,
               season == "Guatemala" ~ 11,
               season == "Panama" ~ 12,
               season == "Cook Islands" ~ 13,
               season == "Fiji" ~ 14,
               season == "China" ~ 15,
               season == "Micronesia" ~ 16,
               season == "Gabon" ~ 17,
               season == "Tocantins" ~ 18,
               season == "Samoa" ~ 19,
               season == "Heroes vs. Villains" ~ 20,
               season == "Nicaragua" ~ 21,
               season == "Redemption Island" ~ 22,
               season == "South Pacific" ~ 23,
               season == "One World" ~ 24,
               season == "Philippines" ~ 25,
               season == "Caramoan" ~ 26,
               season == "Blood vs. Water" ~ 27,
               season == "Cagayan" ~ 28,
               season == "San Juan del Sur" ~ 29,
               season == "Worlds Apart" ~ 30,
               season == "Cambodia" ~ 31,
               season == "Kaôh Rong" ~ 32,
               season == "Millennials vs. Gen X" ~ 33,
               season == "Game Changers" ~ 34,
               season == "Heroes vs. Healers vs. Hustlers" ~ 35,
               season == "Ghost Island" ~ 36,
               season == "David vs. Goliath" ~ 37)
    )

 # Recode NA values for season (which correspond to Kaôh Rong, which has a
 # special character and therefore was not read in correctly) as 32


survivor_data$season_number[is.na(survivor_data$season_number)] <- 32

# Fill out the rest of the data for the 37th season, David vs. Goliath, which
# was still airing when this CSV file was created. First fill out the order in
# which everyone finished

survivor_data[667:673, 6] <- c(5, 3, 7, 6, 4, 2, 1)

# Populate the data for the number of individual challenge wins, gathered from
# the Wikipedia article for Season 37:
# https://en.wikipedia.org/wiki/Survivor:_David_vs._Goliath. Make this a
# numerical vector so that we can reuse it

individualWins <-c(3, 3, 3, 5, 4, 6, 6)

# Populate the data for the number of individualChallengeWins

survivor_data[667:673, 7] <- individualWins

# Populate the data for the number of totalWins by creating a numerical vector
# of the tribalChallengewins and adding it to the number in the corresponding
# position in the individualWins numerical vector

survivor_data[667:673, 8] <- individualWins + survivor_data[667:673, 7]

# Populate the number of days lasted using information from the aforementioned
# Wiki article

survivor_data[667:673, 9] <- c( 37, 39, 35, 36, 38, 39, 39)

# Populate the total number of votes each player received by the end of 39 days
# or whenever they were eliminated

survivor_data[667:673, 10] <- c( 18, 6, 13, 0, 6, 1, 0)
```


```{r cleanup_immunity idols, message= FALSE, error= FALSE}

idols <- read_csv("idols_survivor_clean.csv") %>%
  clean_names() %>%
  select(contestant, season, idols_found, idols_played)

idol_regex <- START %R% "S" %R% capture(DGT %R% DGT) %R% END

idols_clean <- idols %>%
  filter(season != "S38",
         !is.na(contestant),
         !is.na(season),
         season != "Totals") %>%
  mutate(season_number = as.numeric(str_match(season, pattern = idol_regex)[,2]))

  
idols_clean[26, 1] <- c("J.T. Thomas")
idols_clean[81, 1] <- c("J.T. Thomas")


all_data <- left_join(survivor_data, idols_clean,
                      by = c("contestant", "season_number"),
                      suffix = c(".x", ".y"))

all_data <- all_data %>%
  select(-season.y, -iconPictureURL, -fullPictureURL)

# Write as a CSV to use for the shiny App later

# Change the season column to a factor

all_data$season.x <- as.factor(all_data$season.x)

# Change the NA values created through the join in the idols_found column to 0

all_data$idols_found[is.na(all_data$idols_found)] <- 0

# Change the NA values created through the join in the idols_played column to 0

all_data$idols_played[is.na(all_data$idols_played)] <- 0

all_data$finish <- as.numeric(as.character(all_data$finish))
```

```{r geocoding, message = FALSE, warning = FALSE}

# Select only for the hometown column and find the distinct hometowns

geocoded <- all_data %>%
  select(hometown) %>%
  distinct() %>%
  
  # Use ggmap's geocoding functionality using the Google Maps Geocoding API to
  # encode longitude and latitude values for the given cities and states. You
  # may need to use the register_google() function, passing in your hashed API
  # key as the argument.
  
  mutate_geocode(hometown)

# Merge the geocoded information with the original data

geo_join <- left_join(all_data, geocoded, by = "hometown")

# Write to an rds file to read through the shiny app later

write_rds(geo_join, "geo_join.rds")
```
